services:
  api:
    build: .
    image: nerd-event-scheduler-api
    container_name: nerd-event-scheduler-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
